# Generated by Django 5.1.6 on 2025-03-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=150)),
                ('Phone', models.PositiveIntegerField(max_length=50, null=True)),
                ('Title', models.CharField(max_length=100)),
                ('Text', models.TextField()),
            ],
        ),
    ]
