# Generated by Django 5.1.6 on 2025-03-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='Phone',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
